/**
 * DisplayDisclaimer renders a standardized footer disclaimer warning
 * users that the AI-generated content is fictional and non-authoritative.
 */
export function DisplayDisclaimer() {
  return (
    <section className="text-sm text-gray-500 italic pt-4 border-t border-gray-200 mt-8">
      <AIContentNotice />
      <CopyrightNotice />
      <FactualNotice />
    </section>
  );
}

/** Warns that the content is generated by AI and may be unreliable. */
function AIContentNotice() {
  return (
    <p>
      This content was generated using AI and may be incomplete, incorrect, or
      misleading. It is provided for entertainment and demonstration purposes
      only.
    </p>
  );
}

/** Disclaims association with any copyright-protected media used in generation. */
function CopyrightNotice() {
  return (
    <p className="mt-2">
      Characters, locations, and storylines depicted in this experience may be
      derived from or inspired by copyrighted media. All related trademarks and
      copyrights are the property of their respective owners.
    </p>
  );
}

/** Advises users not to treat the content as factual. */
function FactualNotice() {
  return (
    <p className="mt-2">
      Please do not rely on this content as a source of factual information.
    </p>
  );
}
