
export function StoryTopicSelectForm({
  selectedTopic,
  setSelectedTopic,
  handleStartStory,
  loading,
  topics,
}: {
  selectedTopic: string | null;
  setSelectedTopic: (topic: string) => void;
  handleStartStory: () => void;
  loading: boolean;
  topics: string[];
}) {
  return (
    <>
      <div className="bg-gray-50 border rounded-lg shadow-md p-6 flex flex-col md:flex-row items-center justify-center gap-4 w-full max-w-3xl mx-auto text-sm">
        <h2 className="text-xl font-light text-gray-500 whitespace-nowrap">Tell me a story</h2>
        <select
          value={selectedTopic ?? ""}
          onChange={(e) => setSelectedTopic(e.target.value)}
          disabled={loading}
          className="appearance-none border border-gray-300 rounded-lg bg-white px-4 py-3 w-full md:w-auto text-lg focus:outline-none focus:ring-2 focus:ring-indigo-300 transition"
        >
          <option value="" disabled>Select a topic</option>
          {topics.map((topic) => (
            <option key={topic} value={topic}>
              {topic}
            </option>
          ))}
        </select>
        <button
          type="button"
          onClick={handleStartStory}
          disabled={loading || !selectedTopic}
          className={`bg-indigo-400 hover:bg-indigo-500 text-white font-bold py-3 px-8 rounded-lg text-lg transition ${selectedTopic ? "" : "opacity-50 cursor-not-allowed"}`}
        >
          {loading ? "Thinking..." : "Start"}
        </button>
      </div>
      <div className="p-6 flex flex-col md:flex-row items-center justify-center gap-4 w-full max-w-3xl mx-auto text-sm text-gray-400">
        This story is generated by AI and may not be accurate or complete, despite clear instructions its best efforts. Please be cautious
        and use your discernment.
      </div>
    </>
  );
}
